__author__ = 'dipap'


BUSINESS_SECTORS = (
    ('', ''),
    ('Accountants', 'Accountants'),
    ('Advertising/Public Relations', 'Advertising/Public Relations'),
    ('Aerospace, Defense Contractors', 'Aerospace, Defense Contractors'),
    ('Agribusiness', 'Agribusiness'),
    ('Agricultural Services & Products', 'Agricultural Services & Products'),
    ('Agriculture', 'Agriculture'),
    ('Air Transport', 'Air Transport'),
    ('Airlines', 'Airlines'),
    ('Alcoholic Beverages', 'Alcoholic Beverages'),
    ('Alternative Energy Production & Services', 'Alternative Energy Production & Services'),
    ('Architectural Services', 'Architectural Services'),
    ('Attorneys/Law Firms', 'Attorneys/Law Firms'),
    ('Auto Dealers', 'Auto Dealers'),
    ('Auto Manufacturers', 'Auto Manufacturers'),
    ('Automotive', 'Automotive'),
    ('Banking, Mortgage', 'Banking, Mortgage'),
    ('Banks, Commercial', 'Banks, Commercial'),
    ('Banks, Savings & Loans', 'Banks, Savings & Loans'),
    ('Bars & Restaurants', 'Bars & Restaurants'),
    ('Books, Magazines & Newspapers', 'Books, Magazines & Newspapers'),
    ('Broadcasters, Radio/TV', 'Broadcasters, Radio/TV'),
    ('Builders', 'Builders'),
    ('Building Materials & Equipment', 'Building Materials & Equipment'),
    ('Business Services', 'Business Services'),
    ('Cable & Satellite TV Production & Distribution', 'Cable & Satellite TV Production & Distribution'),
    ('Casinos / Gambling', 'Casinos / Gambling'),
    ('Cattle Ranchers/Livestock', 'Cattle Ranchers/Livestock'),
    ('Chemical & Related Manufacturing', 'Chemical & Related Manufacturing'),
    ('Chiropractors', 'Chiropractors'),
    ('Civil Servants/Public Officials', 'Civil Servants/Public Officials'),
    ('Clergy & Religious Organizations ', 'Clergy & Religious Organizations '),
    ('Clothing Manufacturing', 'Clothing Manufacturing'),
    ('Coal Mining', 'Coal Mining'),
    ('Colleges, Universities & Schools', 'Colleges, Universities & Schools'),
    ('Commercial TV & Radio Stations', 'Commercial TV & Radio Stations'),
    ('Communications/Electronics', 'Communications/Electronics'),
    ('Computer Software', 'Computer Software'),
    ('Construction', 'Construction'),
    ('Construction Services', 'Construction Services'),
    ('Construction Unions', 'Construction Unions'),
    ('Credit Unions', 'Credit Unions'),
    ('Crop Production & Basic Processing', 'Crop Production & Basic Processing'),
    ('Cruise Ships & Lines', 'Cruise Ships & Lines'),
    ('Dairy', 'Dairy'),
    ('Defense', 'Defense'),
    ('Defense Electronics', 'Defense Electronics'),
    ('Defense/Foreign Policy Advocates', 'Defense/Foreign Policy Advocates'),
    ('Dentists', 'Dentists'),
    ('Doctors & Other Health Professionals', 'Doctors & Other Health Professionals'),
    ('Drug Manufacturers', 'Drug Manufacturers'),
    ('Education ', 'Education '),
    ('Electric Utilities', 'Electric Utilities'),
    ('Electronics Manufacturing & Equipment', 'Electronics Manufacturing & Equipment'),
    ('Electronics, Defense Contractors', 'Electronics, Defense Contractors'),
    ('Energy & Natural Resources', 'Energy & Natural Resources'),
    ('Entertainment Industry', 'Entertainment Industry'),
    ('Environment ', 'Environment '),
    ('Finance / Credit Companies', 'Finance / Credit Companies'),
    ('Finance, Insurance & Real Estate', 'Finance, Insurance & Real Estate'),
    ('Food & Beverage', 'Food & Beverage'),
    ('Food Processing & Sales', 'Food Processing & Sales'),
    ('Food Products Manufacturing', 'Food Products Manufacturing'),
    ('Food Stores', 'Food Stores'),
    ('Forestry & Forest Products', 'Forestry & Forest Products'),
    ('Funeral Services', 'Funeral Services'),
    ('Garbage Collection/Waste Management', 'Garbage Collection/Waste Management'),
    ('Gas & Oil', 'Gas & Oil'),
    ('General Contractors', 'General Contractors'),
    ('Hedge Funds', 'Hedge Funds'),
    ('HMOs & Health Care Services', 'HMOs & Health Care Services'),
    ('Home Builders', 'Home Builders'),
    ('Hospitals & Nursing Homes', 'Hospitals & Nursing Homes'),
    ('Hotels, Motels & Tourism', 'Hotels, Motels & Tourism'),
    ('Human Rights ', 'Human Rights '),
    ('Industrial Unions ', 'Industrial Unions '),
    ('Insurance', 'Insurance'),
    ('Labor', 'Labor'),
    ('Lawyers / Law Firms', 'Lawyers / Law Firms'),
    ('Livestock', 'Livestock'),
    ('Logging, Timber & Paper Mills', 'Logging, Timber & Paper Mills'),
    ('Manufacturing', 'Manufacturing'),
    ('Marine Transport', 'Marine Transport'),
    ('Meat processing & products', 'Meat processing & products'),
    ('Medical Supplies', 'Medical Supplies'),
    ('Mining', 'Mining'),
    ('Mortgage Bankers & Brokers', 'Mortgage Bankers & Brokers'),
    ('Motion Picture Production & Distribution', 'Motion Picture Production & Distribution'),
    ('Music Production', 'Music Production'),
    ('Natural Gas Pipelines', 'Natural Gas Pipelines'),
    ('Newspaper, Magazine & Book Publishing', 'Newspaper, Magazine & Book Publishing'),
    ('Nurses', 'Nurses'),
    ('Nursing Homes/Hospitals', 'Nursing Homes/Hospitals'),
    ('Nutritional & Dietary Supplements', 'Nutritional & Dietary Supplements'),
    ('Oil & Gas', 'Oil & Gas'),
    ('Other', 'Other'),
    ('Pharmaceuticals / Health Products', 'Pharmaceuticals / Health Products'),
    ('Phone Companies', 'Phone Companies'),
    ('Physicians & Other Health Professionals', 'Physicians & Other Health Professionals'),
    ('Postal Unions', 'Postal Unions'),
    ('Power Utilities', 'Power Utilities'),
    ('Printing & Publishing', 'Printing & Publishing'),
    ('Private Equity & Investment Firms', 'Private Equity & Investment Firms'),
    ('Professional Sports, Sports Arenas & Related Equipment & Services', 'Professional Sports, Sports Arenas & Related Equipment & Services'),
    ('Railroads', 'Railroads'),
    ('Restaurants & Drinking Establishments', 'Restaurants & Drinking Establishments'),
    ('Retail Sales', 'Retail Sales'),
    ('Software development', 'Software development'),
    ('Retired ', 'Retired '),
    ('Stock Brokers/Investment Industry', 'Stock Brokers/Investment Industry'),
    ('Telecom Services & Equipment', 'Telecom Services & Equipment'),
    ('Tobacco', 'Tobacco'),
    ('Transportation', 'Transportation'),
)

WORK_POSITIONS = (
    ('', ''),
    ('Computing Consultant', 'Computing Consultant'),
    ('Conservation Technician', 'Conservation Technician'),
    ('Development Technologist', 'Development Technologist'),
    ('Drug Evaluator', 'Drug Evaluator'),
    ('Exploration Director', 'Exploration Director'),
    ('Field Technician', 'Field Technician'),
    ('Financial Analyst', 'Financial Analyst'),
    ('Genetic Counselor', 'Genetic Counselor'),
    ('Grants/Proposal Writer', 'Grants/Proposal Writer'),
    ('Groundwater Technician', 'Groundwater Technician'),
    ('Hardware Designer', 'Hardware Designer'),
    ('Health Research Assistant', 'Health Research Assistant'),
    ('Health Technology Assistant', 'Health Technology Assistant'),
    ('Hospital Accounting Analyst', 'Hospital Accounting Analyst'),
    ('Hospital Research Assistant', 'Hospital Research Assistant'),
    ('IT Support Staff', 'IT Support Staff'),
    ('Institutional Research Director', 'Institutional Research Director'),
    ('Insurance Representative', 'Insurance Representative'),
    ('Intranet Specialist', 'Intranet Specialist'),
    ('Intranet Support', 'Intranet Support'),
    ('Junior Analyst', 'Junior Analyst'),
    ('Laboratory Assistant', 'Laboratory Assistant'),
    ('Laboratory Instructor', 'Laboratory Instructor'),
    ('Laboratory Technician', 'Laboratory Technician'),
    ('Operations Team Leader', 'Operations Team Leader'),
    ('Operations Unit Manager', 'Operations Unit Manager'),
    ('Organic Lab Research Assistant', 'Organic Lab Research Assistant'),
    ('Organic Lab Worker', 'Organic Lab Worker'),
    ('Pharmaceutical Assistant', 'Pharmaceutical Assistant'),
    ('Pharmaceutical Marketing Assistant', 'Pharmaceutical Marketing Assistant'),
    ('Pharmaceutical Research Analyst', 'Pharmaceutical Research Analyst'),
    ('Pharmaceutical Research Assistant', 'Pharmaceutical Research Assistant'),
    ('Pharmaceutical Research Technician', 'Pharmaceutical Research Technician'),
    ('Pharmaceutical Technician', 'Pharmaceutical Technician'),
    ('Pharmacy Affairs Assistant', 'Pharmacy Affairs Assistant'),
    ('Pharmacy Assistant', 'Pharmacy Assistant'),
    ('Pharmacy Innovation Assistant', 'Pharmacy Innovation Assistant'),
    ('Power Regulator', 'Power Regulator'),
    ('Process Inspector', 'Process Inspector'),
    ('Process Research Manager', 'Process Research Manager'),
    ('Product Test Specialist', 'Product Test Specialist'),
    ('Production Team Leader', 'Production Team Leader'),
    ('Production Test Supervisor', 'Production Test Supervisor'),
    ('Professional Programs Assistant', 'Professional Programs Assistant'),
    ('Project Manager', 'Project Manager'),
    ('Quality Assistant', 'Quality Assistant'),
    ('Quality Assurance Manager', 'Quality Assurance Manager'),
    ('Quality Assurance Technologist', 'Quality Assurance Technologist'),
    ('Quality Control Analyst', 'Quality Control Analyst'),
    ('Quality Control Manager', 'Quality Control Manager'),
    ('Quality Control Supervisor', 'Quality Control Supervisor'),
    ('Regulatory Affairs Associate', 'Regulatory Affairs Associate'),
    ('Rehabilitation Engineering Assistant', 'Rehabilitation Engineering Assistant'),
    ('Reimbursement Analyst', 'Reimbursement Analyst'),
    ('Research Assistant', 'Research Assistant'),
    ('Research Technician', 'Research Technician'),
    ('Research and Development Associate', 'Research and Development Associate'),
    ('Research and Development Director', 'Research and Development Director'),
    ('Research and Development Manager', 'Research and Development Manager'),
    ('Research and Development Supervisor', 'Research and Development Supervisor'),
    ('Research and Development Technician', 'Research and Development Technician'),
    ('Research and Development Tester', 'Research and Development Tester'),
    ('Researcher', 'Researcher'),
    ('Retail Analyst', 'Retail Analyst'),
    ('Sales Analyst', 'Sales Analyst'),
    ('Satellite Data Analyst', 'Satellite Data Analyst'),
    ('Science Technician', 'Science Technician'),
    ('Scientific Artist', 'Scientific Artist'),
    ('Senior Pharmacy Student', 'Senior Pharmacy Student'),
    ('Software Developer', 'Software Developer'),
    ('Software Engineering Assistant', 'Software Engineering Assistant'),
    ('Solid Waste Field Technician', 'Solid Waste Field Technician'),
    ('Special Projects Coordinator', 'Special Projects Coordinator'),
    ('Statistician', 'Statistician'),
    ('Structural Engineer', 'Structural Engineer'),
    ('Systems Analyst', 'Systems Analyst'),
)

INFLUENCES = (
    ('Family & relatives', 'Family & relatives'),
    ('Friends & social circle', 'Friends & social circle'),
    ('Co-workers', 'Co-workers'),
    ('Advertisement', 'Advertisement'),
    ('TV & Media', 'TV & Media'),
    ('Blogs', 'Blogs'),
    ('Other', 'Other'),
)

DEVICES = (
    ('PC', 'PC'),
    ('Laptop', 'Laptop'),
    ('Tablet', 'Tablet'),
    ('Mobile phone', 'Mobile phone'),
    ('Wearable', 'Wearable'),
)

PLATFORMS = (
    ('MS Windows', 'MS Windows'),
    ('OS X', 'OS X'),
    ('Linux', 'Linux'),
    ('iOS', 'iOS'),
    ('Android', 'Android'),
)

BROWSERS = (
    ('Internet Explorer', 'Internet Explorer'),
    ('Firefox', 'Firefox'),
    ('Chrome', 'Chrome'),
    ('Safari', 'Safari'),
)

TECH_LEVELS = (
    ('Beginner', 'Beginner'),
    ('Intermediate', 'Intermediate'),
    ('Expert', 'Expert'),
    ('Geek', 'gEEk'),
)
DEFAULT_BRANDS = (
    ('Facebook', 'Facebook'),
    ('Twitter', 'Twitter'),
    ('Google', 'Google'),
    ('Instagram', 'Instagram'),
    ('Apple', 'Apple'),
)

BRAND_OPINIONS = (
    ('P', 'Positive'),
    ('-', 'Neutral'),
    ('N', 'Negative'),
)


INVITATION_STATUS = (
    ('PENDING', 'Pending'),
    ('ACCEPTED', 'Accepted'),
)
